### ISSUE TITLE
writeMEA: "Error in 1:(lag0 - 1) : argument of length 0"

### ISSUE THREAD

**Issue by thekryz** [kleinbub/rMEA#1]
I try to use writeMEA on a MEAlist object as follows, but end up with an error message:

```
> class(meaobject)
[1] "MEAlist"

> tempccf <- rMEA::MEAccf(meaobject, lagSec = 5, winSec = 60, incSec = 30, r2Z = TRUE, ABS = TRUE)  Computing CCF: ..................................................\|100% ..................................................\|Done ;)

> rMEA::writeMEA(tempccf, save.directory = "H:\\test", mea_data = TRUE, ccf_data = TRUE)
Exporting 1 dyads
..................................................|100%
..................................................|Done ;)
Fehler in 1:(lag0 - 1) : Argument der Länge 0
```

I think the english equivalent of the error should read:
`Error in 1:(lag0 - 1) : argument of length 0`

What am I doing wrong?

> version information:
> R: 3.6.3
> RStudio: 1.2.5033
> rMEA: 1.1.0

**Comment by thekryz** [comment]
More details:

The problem happens in writeMEA.MEA in the line
`Qccf$leading = apply(Qccf[1:(lag0 - 1)], 1, mean, na.rm = T)`

lag0 is
`integer(0)`
because there is no actual column named `lag0`. The closest ones are called
```
lag-0.0116783450116782
lag0.00500500500500519
```

I figured that the problem is with the sampling rate I used: 59.94. Since it's not an integer, it seems to produce lag columns that don't match up with what's expected. I turned the sampling rate to 60 and it seems to work.

I suggest a mechanism that checks whether the sampling rate is an integer and either providing an error message or applying a circumventing measure in functions that create the column names for the lags.

**Comment by thekryz** [comment]
Maybe, when assigning lag-column-numbers, it doesn't start with 0 but starts with the lowest (or highest) value. This might lead to there not being a lag0. Maybe creating the column-names could start from 0 and then extend into negative and positive - that could solve the issue and account for non-integer framerates.

**Comment by kleinbub** [comment]
@thekryz that syntax is for a older version of the package. Now you can either export the raw data or the ccf data using:
`writeMEA(tempccf, save.directory = save_path, what="mea")`
or
`writeMEA(tempccf, save.directory = save_path, what="ccf")`
please let me know if you still need help
