### ISSUE TITLE
Feature request: function to export Cohen's d

### ISSUE THREAD

**Issue by thekryz** [kleinbub/rMEA#3]
The real "result" of a synchrony analysis seems to be the effect size, Cohen's d, either in a group comparison or compared to pseudosynchrony. However, there is no function so far to directly export Cohen's d or to even just return it as a number - all I can find is the inclusion in the MEAdistplot function.

I would therefor suggest a function to return and export these values.

**Comment by kleinbub** [comment]
@thekryz sorry for the late reply, I had misconfigured notifications settings. 
It's easy to calculate cohen's d from two MEAlist objects (mea1, mea2) with the cohens_d function provided in the package:
`
ccf1 = getCCF(mea1,"grandAver");
ccf2 = getCCF(mea2,"grandAver");
cohens_d(ccf1, ccf2)
`
While I may implement a `cohensD(mea1, mea2)` I feel it would be ambiguous on exactly what data the effect size is calculated. Whereas having to extract the values manually 'forces' the user to understand what he's doing.
I'd love to know your thoughts though.
