### ISSUE TITLE
shuffle & keepRoles: Doesn't combine all possible options (while keeping the roles)

### ISSUE THREAD

**Issue by thekryz** [kleinbub/rMEA#6]
Hello and first of all: Thank you for quickly implementing this feature!

I tested it and had one issue. Let's say I have dyads A, B and C, each with two time series, one per participant (s1 and s2). With the shuffle function, when setting size to a high value (e.g. 99999999), I would expect to receive all possible combinations in return. With keepRoles, I'd expect s1 and s2 to remain on their respective sides. These would be the combinations I'd expect:

```
A(s1) - B(s2)
A(s1) - C(s2)
B(s1) - A(s2)
B(s1) - C(s2)
C(s1) - A(s2)
C(s1) - B(s2)
```

However, shuffle only gives me:

```
A(s1) - B(s2)
A(s1) - C(s2)
B(s1) - A(s2)
B(s1) - C(s2)
```

It's either a bug or I am overlooking a reason as to skip some combinations.

Thank you!

**Comment by kleinbub** [comment]
@thekryz sorry for late reply. I did some testing and I am not able to replicate the issue. If I'm not wrong, with keepRoles = TRUE, the maximum number of combinations is n*(n-1), so in your example 6, and I am getting all of them with the demo data included in the package. 
Could you double check if you are actually getting a lower number with your dataset?
Thank you!
