### ISSUE TITLE
Feature request for MEAlagplot: attribute to allow drawing means only

### ISSUE THREAD

**Issue by c-hoffmann** [kleinbub/rMEA#7]
With lots of data, the MEAlagplot can become somewhat cluttered. One way to make it look clearer would be to allow for all the single-window synchrony-curves in the background to be excluded from the graph and therefore have the mean curves on a white background. My question is: Would it be possible to implement a switch, such as "meansOnly = F" which can be set to TRUE in order to only print the overall / mean curves?

**Comment by kleinbub** [comment]
Thanks for the suggestion, I've added 2 new parameters to control the transparency of individual lines for main data (mea.alpha) and contrast data (contrast.alpha). The possible values are any numerical value from 0 (invisible lines) to 1 (fully opaque).
If the value is set to zero the drawing is entirely suppressed, so there will be a distinct performance advantage, if you have many lines.
Nevertheless, please take care. Looking at individual lines plays an important diagnostic role in data analysis, e.g. by showing outliers, or peculiar patterns, etc, which could operate an undue influence on results.
Please let me know if this works for you

**Comment by c-hoffmann** [comment]
Thank you for the quick implementation! This is exactly what I needed.
