### ISSUE TITLE
Visualizations function does not work properly

### ISSUE THREAD

**Issue by gokcergun** [kleinbub/rMEA#8]
hi, 

I am using rMEA package (version1.2.2) on my windows computer. R version is 4.2.1
When I use MEAheatmap() function, it puts the legend on the heatmap (overlap)

Is it related to the R version or operating system (windows)?

Thank you.

**Comment by kleinbub** [comment]
@gokcergun this sounds like you are trying to draw in a very small panel. Are you using base R or RStudio? In any case, can you try to make the plot area larger (by click-and-dragging one of the corners or sides) and running the commands again?

**Comment by gokcergun** [comment]
Thank you for your answer. 
I am using RStudio. 
I extended plot area (max), but still have this issue. I also downgraded R version, but it did not solve the problem. 
Perhaps it is related to my default RStudio settings. I will try to change it.

**Comment by gokcergun** [comment]
changing par() parameters of RStudio solved the issue, thank you
