### ISSUE TITLE
question about winTimes.start

### ISSUE THREAD

**Issue by gokcergun** [kleinbub/rMEA#9]
Hi, 
I have a question about winTimes.start/end variable of ccf results. Does it return the real video time? 
It confused me a bit because I would expect the windows to start from 00:00+lagSec, but they always start from 00:00. If the windows start from very beginning, how can -lags be calculated? 

Thank you.

**Comment by kleinbub** [comment]
One series is always fixed at 00:00, the other is shifted forward. With positive lags s1 is fixed and s2 shifted, with negative lags, the opposite.

**Comment by gokcergun** [comment]
> 

Thank you!
